version: "3.5"

services:
  current_time:
    container_name: current_time
    image: current-time-service
    build:
      context: .
      dockerfile: ./current-time-service/docker/Dockerfile
    networks:
      - local
    ports:
      - "8080:8080"

  metrics:
    container_name: metrics
    image: metrics-service
    build:
      context: .
      dockerfile: ./metrics-service/docker/Dockerfile
    networks:
      - local

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - local
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - local
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
    depends_on:
      - zookeeper

networks:
  local:
    driver: bridge
